
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/yu/miniconda/condabin/"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/yu/.dotnet/tools/"
      - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/"
    searched_directories:
      - "/Users/yu/miniconda/condabin/uname"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/yu/miniconda/condabin"
        - "/Users/yu/.nvm/versions/node/v20.19.6/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64"
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Darwin - 25.3.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/Users/yu/miniconda/condabin/"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/yu/.dotnet/tools/"
      - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/"
    searched_directories:
      - "/Users/yu/miniconda/condabin/gmake"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/gmake"
      - "/opt/homebrew/bin/gmake"
      - "/opt/homebrew/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/System/Cryptexes/App/usr/bin/gmake"
      - "/usr/bin/gmake"
      - "/bin/gmake"
      - "/usr/sbin/gmake"
      - "/sbin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/gmake"
      - "/opt/pmk/env/global/bin/gmake"
      - "/Library/Apple/usr/bin/gmake"
      - "/usr/local/share/dotnet/gmake"
      - "/Users/yu/.dotnet/tools/gmake"
      - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts/gmake"
      - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/gmake"
      - "/Users/yu/miniconda/condabin/make"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/make"
      - "/opt/homebrew/bin/make"
      - "/opt/homebrew/sbin/make"
      - "/usr/local/bin/make"
      - "/System/Cryptexes/App/usr/bin/make"
    found: "/usr/bin/make"
    search_context:
      ENV{PATH}:
        - "/Users/yu/miniconda/condabin"
        - "/Users/yu/.nvm/versions/node/v20.19.6/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64"
  -
    kind: "find-v1"
    backtrace:
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/yu/miniconda/condabin/"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/yu/.dotnet/tools/"
      - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/"
    searched_directories:
      - "/Users/yu/miniconda/condabin/install_name_tool"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/yu/miniconda/condabin"
        - "/Users/yu/.nvm/versions/node/v20.19.6/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64"
      CMAKE_INSTALL_PREFIX: "/usr/local"
  -
    kind: "find-v1"
    backtrace:
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/FindGit.cmake:111 (find_program)"
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/ExternalProject/shared_internal_commands.cmake:926 (find_package)"
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-4.2/Modules/ExternalProject.cmake:3258 (_ep_add_download_command)"
      - "CMakeLists.txt:7 (ExternalProject_Add)"
    mode: "program"
    variable: "GIT_EXECUTABLE"
    description: "Git command line client"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "git"
    candidate_directories:
      - "/Users/yu/miniconda/condabin/"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/yu/.dotnet/tools/"
      - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/"
      - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/bin/"
      - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/sbin/"
      - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/homebrew/"
      - "/usr/local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/"
      - "/usr/bin/"
      - "/usr/sbin/"
      - "/usr/"
      - "/bin/"
      - "/sbin/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/sbin/"
      - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/"
      - "/usr/X11R6/bin/"
      - "/usr/X11R6/sbin/"
      - "/usr/X11R6/"
      - "/usr/pkg/bin/"
      - "/usr/pkg/sbin/"
      - "/usr/pkg/"
      - "/opt/bin/"
      - "/opt/sbin/"
      - "/opt/"
      - "/sw/bin/"
      - "/sw/sbin/"
      - "/sw/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/opt/local/"
      - "/Users/yu/Applications/"
      - "/Applications/"
      - "/Applications/Xcode.app/Contents/Applications/"
      - "/Applications/Xcode.app/Contents/Developer/Applications/"
    searched_directories:
      - "/Users/yu/miniconda/condabin/git"
      - "/Users/yu/.nvm/versions/node/v20.19.6/bin/git"
      - "/opt/homebrew/bin/git"
      - "/opt/homebrew/sbin/git"
      - "/usr/local/bin/git"
      - "/System/Cryptexes/App/usr/bin/git"
    found: "/usr/bin/git"
    search_context:
      ENV{PATH}:
        - "/Users/yu/miniconda/condabin"
        - "/Users/yu/.nvm/versions/node/v20.19.6/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Users/yu/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/yu/Applications/CLion.app/Contents/bin/ninja/mac/aarch64"
      CMAKE_INSTALL_PREFIX: "/usr/local"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr"
        - "/"
        - "/Users/yu/Applications/CLion.app/Contents/bin/cmake/mac/aarch64"
        - "/usr/local"
        - "/usr/X11R6"
        - "/usr/pkg"
        - "/opt"
        - "/sw"
        - "/opt/local"
      CMAKE_SYSTEM_APPBUNDLE_PATH:
        - "/Users/yu/Applications"
        - "/Applications"
        - "/Applications/Xcode.app/Contents/Applications"
        - "/Applications/Xcode.app/Contents/Developer/Applications"
...
